channels:
  - conda-forge
  - openalea3
dependencies:
  - conda-forge
  - openalea.plantgl
  - pyqglviewer
  - numpy
  - scipy
  - qtconsole
  - pandas
  - matplotlib
  - openalea.sconsx
  - networkx
  - ipykernel
  - ipyparallel
