{% set pyproject = load_file_data('pyproject.toml') %}
{% set description = pyproject.get('project').get('description') %}
{% set home = pyproject.get('project', {}).get('urls').get('Homepage') %}

{% set major = load_file_regex(
  load_file="src/openalea/visualea/version.py",
  regex_pattern='MAJOR = (.+)') %}
{% set minor = load_file_regex(
  load_file="src/openalea/visualea/version.py",
  regex_pattern='MINOR = (.+)') %}
{% set post = load_file_regex(
  load_file="src/openalea/visualea/version.py",
  regex_pattern='POST = (.+)') %}

{% set version = major[ 1 ]+'.'+minor[ 1 ]+'.'+post[ 1 ] %}

package:
  name: openalea.visualea
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  preserve_egg_dir: True
  number: 1
  script: {{PYTHON}} -m pip install .

requirements:
  build:
    - python {{PY_VER}}
    - setuptools
    - openalea.deploy
  run:
    - python  x.x
    - openalea.deploy
    - openalea.core
    - openalea.oalab
    - openalea.grapheditor
    - openalea.stdlib

test:
  imports:
    - openalea.visualea
    - openalea.visualea.qt

about:
  home: {{ home }}
  license: CeCILL-C
  summary: {{ description }}
