{% set data = load_setup_py_data() %}

package:
  name: openalea.visualea
  version: {{ data.get('version') }}

source:
  path: ..

build:
  #noarch: python,# issue 37
  preserve_egg_dir: True
  number: 1
  script: {{PYTHON}} setup.py install

requirements:
  build:
    - python {{PY_VER}}
    - setuptools
    - openalea.deploy
  run:
    - python  <3.11
    - openalea.deploy
    - openalea.core
    - openalea.oalab
    - openalea.grapheditor
    - openalea.stdlib


test:
  imports:
    - openalea.visualea
    - openalea.visualea.qt

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}

