name: visualea
channels:
  - conda-forge
  - openalea3
dependencies:
  - python
  - openalea.deploy
  - openalea.core
  - openalea.oalab
  - openalea.grapheditor
  - openalea.stdlib
  - pip
  - pip:
    - -e ..[doc]
